# Generated by Django 6.0.1 on 2026-01-29 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_college_declaration_document_college_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='id_photo',
            field=models.FileField(blank=True, null=True, upload_to='user_id_photos/'),
        ),
    ]
