# Generated by Django 6.0.1 on 2026-01-29 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_appuser_id_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_photo',
            field=models.FileField(blank=True, null=True, upload_to='event_photo/'),
        ),
    ]
