# Generated by Django 6.0.1 on 2026-01-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_event_event_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='subevent',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
