# Generated by Django 6.0.1 on 2026-01-29 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='verification_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
