# Generated by Django 6.0.1 on 2026-02-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_appuser_verification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='profile_pic',
            field=models.FileField(blank=True, null=True, upload_to='user_profile_pics/'),
        ),
    ]
